version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend-react
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./server
    container_name: server-node
    restart: always
    ports:
      - "3173:3173"
    stdin_open: true
    tty: true
    depends_on:
      - database

  database:
    image: mongo
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /mnt/nas/mongo:/data/db